### ISSUE TITLE
What can i do with TS3 Hook?

### ISSUE THREAD

**Issue by GitSimonHub** [TeaSpeak/TS3Hook#37]
Hey,

where can i see, everything that i can do with the T 3 Hook, like change version, hide IP etc.
Thanks

**Comment by GitSimonHub** [comment]
Only this?
Or can you hide more infos, or do some more things.
It is possible to crash someones Teamspeak if he checks my client informations?

**Comment by Bluscream** [comment]
https://github.com/Bluscream/pyTSon_plugins/tree/master/scripts/crasher_3_1_7

**Comment by GitSimonHub** [comment]
do i need to downgrade my ts3 for the crasher?

**Comment by Bluscream** [comment]
Please refer to https://github.com/Bluscream/pyTSon_plugins/issues/20#issuecomment-390629866
