### ISSUE TITLE
Change client connection infos?

### ISSUE THREAD

**Issue by GitSimonHub** [TeaSpeak/TS3Hook#39]
Is it possible to change (not hide) the client connection infos?
So that the ping is for example 1337?

Thanks

**Comment by Bluscream** [comment]
Yes, https://github.com/Bluscream/pyTSon_plugins/blob/master/scripts/crasher_3_1_7/__init__.py#L89

**Comment by GitSimonHub** [comment]
How does it work?
Is there an Tutorial

**Comment by Bluscream** [comment]
No there is and won't be a tutorial. It's open source
